config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get 'home/index'

  resources :recipes do
    resources :ingredients
  end

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  # attr_accessor :recipe_id, :ingredient_id
  belongs_to :recipe, optional: true
  validates :name, presence: true, length: { minimum: 3 }
  validates :amount, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # attr_accessor :name, :ingredients_attributes
  has_many :ingredients, :dependent => :delete_all
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  validates :title, presence: true, length: {minimum: 4}
  validates :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def new
    @ingredient = Ingredient.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.create(ingredient_params)
    redirect_to edit_recipe_path(@recipe)
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
  end

  private
  def ingredient_params
    params.require(:ingredient).permit(:name, :amount, :uom)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @recipe.ingredients.build
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @recipe.ingredients.build
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to edit_recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to edit_recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to @recipe
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :author, :note,
                                   ingredients_attributes: [:id, :name, :amount, :uom, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/pantry_helper.rb
module PantryHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/_ingredient_form.html.erb
<%= form_with do |form| %>
  <%= form.label :name, "Name" %>
  <%= form.text_field :name %>

  <%= form.label :amount, "Amount" %>
  <%= form.number_field :amount %> </br>

  <%= form.label :uom, "UOM" %>
  <%= form.text_field :uom %>  </br>

  <%= form.label :_destroy, "Remove" %>
  <%= form.check_box :_destroy %>
  <%= form.submit %>
<% end %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<!--<link rel="stylesheet" type="text/css" href="app/assets/stylesheets/home.scss">-->

<div id = "page-container">
  <div class = "header">
    <h2> Meal Planner</h2>
  </div>

  <div id = "content-wrap">
    <div id = "left">
      <fieldset id = "pantry">

        <h2>Your Pantry:</h2>
        <input class='btn' type="button" id = 'add_btn' onclick="newForm()" value="Add"><br>

        <form id = "ingredient_0">

          <fieldset id="item_box">
            Name: <input type="text" name="iname">
            Amount: <input type="text" name="iamount"><br>
            UOM: <input type = "text" name="iuom">
            <input class='btn' type="button" id = "0" onclick="removeForm(this.id)" value="delete">
          </fieldset>
        </form>

      </fieldset><br>

      <form method="post">
        <input type="button" name="search" id="search_btn" value="Find Recipes"/><br>
      </form>

    </div>

    <fieldset id = "recipes">
      <h2>Recipes</h2><br>
      <%= link_to '<button class="btn" type="button">See All Recipes </button>'.html_safe, controller: 'recipes' %>
    </fieldset>
  </div>

  <footer id = "footer">Team Eggplantbert: Alex Eby, Tristin Colenso, Ethan Large, Roman Formicola</footer>
</div>
</html>

<script>
    var ing_total = 0;
    function newForm() {
        var old_id = ing_total.toString();
        ing_total++;
        var div = document.createElement('div');
        div.setAttribute('id', 'ingredient_' + ing_total);
        div.innerHTML = document.getElementById('ingredient_0').innerHTML;

        //var r_btn = div.getElementById(old_id);
        //r_btn.setAttribute('id', ing_total.toString());

        document.getElementById('pantry').appendChild(div);
    }
    function removeForm(clicked_id) {
      alert(clicked_id);
    }

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MealPlannerSql</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= javascript_include_tag :defaults, :cache => true %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<!--<link rel="stylesheet" type="text/css" href="app/assets/stylesheets/form.css">-->
<div id = "form">
  <%= form_for(@recipe) do |form| %>
    <% if @recipe.errors.any? %>
      <div id = "error_explanation">
        <h2>
          <%= pluralize(@recipe.errors.count, "error") %>
          prohibited this recipe from being saved:
        </h2>
        <ul>
          <%@recipe.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= form.label :title  %><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :author  %><br>
      <%= form.text_field :author %>
    </p>

    <p>
      <%= form.label :note %><br>
      <%= form.text_area :note %>
    </p>
    <h2 id = "add">Add an Ingredient: </h2>
    <%= form.fields_for :ingredients do |builder| %>
      <%= render 'ingredient_fields', form: builder %>
    <% end %>
    <p>
      <%= form.submit %>
    </p>

  <% end %>
</div>

app/views/recipes/_ingredient_fields.html.erb
<!--<link rel="stylesheet" type="text/css" href="app/assets/stylesheets/ingredient_form.css">-->

<p>
  <%= form.label :name, "Name" %>
  <%= form.text_field :name %>

  <%= form.label :amount, "Amount" %>
  <%= form.number_field :amount %>

  <%= form.label :uom, "UOM" %>
  <%= form.text_field :uom %>

  <%= form.label :_destroy, "Remove" %>
  <%= form.check_box :_destroy %>
</p>

app/views/recipes/edit.html.erb
<!--<link rel="stylesheet" type="text/css" href="app/assets/stylesheets/form.css">-->

<div id = "page-container">
  <header id = "header"> <%= @recipe.title %> </header>

  <div id = "content-wrap">
    <%= render 'form' %>
  </div>

  <%= link_to '<button type="button">Done</button>'.html_safe, recipes_path %>
  <footer id = "footer">Team Eggplantbert: Alex Eby, Tristin Colenso, Ethan Large, Roman Formicola</footer>
</div>

app/views/recipes/index.html.erb
<!--<link rel="stylesheet" type="text/css" href="app/assets/stylesheets/recipes.scss">-->

<div id = "page-container">
  <div class = 'header'>
    Listing Recipes
  </div>
  <div id = "content-wrap">

    <%= link_to '<button type="button">Home</button>'.html_safe, home_index_path %>

    <table>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Note</th>
        <th colspan="3"></th>
      </tr>

      <% @recipes.each do |recipe| %>
        <tr>
          <td><%= recipe.title %></td>
          <td><%= recipe.author  %></td>
          <td><%= recipe.note %></td>
          <td><%= link_to 'Show', recipe_path(recipe) %></td>
          <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
          <td><%= link_to 'Destroy', recipe_path(recipe),
                          method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
      <% end %>
    </table>
    </br>
    <%= link_to '<button type="button">New Recipe</button>'.html_safe, new_recipe_path %>
    </br>
  </div>

  <footer id = "footer">Team Eggplantbert: Alex Eby, Tristin Colenso, Ethan Large, Roman Formicola</footer>
</div>

app/views/recipes/new.html.erb
<!--<link rel="stylesheet" type="text/css" href="app/assets/stylesheets/form.css">-->

<div id = "page-container">
  <header id = "header"> New Recipe </header>
  <div id = "content-wrap">

    <%= render 'form' %>


  </div>
  <%= link_to '<button id = "back" type="button">Back</button>'.html_safe, recipes_path %>
  <footer id = "footer">Team Eggplantbert: Alex Eby, Tristin Colenso, Ethan Large, Roman Formicola</footer>
</div>

app/views/recipes/show.html.erb
<!--<link rel="stylesheet" type="text/css" href="app/assets/stylesheets/show.css">-->

<div id = "page-container">
  <header id = "title">
    <%= @recipe.title %>
  </header>

  <div id = "content-wrap">
    <p class = "label">
      <strong>Author: </strong>
      <%= @recipe.author %>
    </p>

    <p  class = "label">
      <strong> Note: </strong>
      <%= @recipe.note  %>
    </p>


    <table>
      <h2 class = "label">Ingredients</h2>
      <tr>
        <th>Name</th>
        <th>Amount</th>
        <th>UOM</th>
      </tr>

      <% @recipe.ingredients.each do |ingredient| %>
        <tr>
          <td><%= ingredient.name %></td>
          <td><%= ingredient.amount  %></td>
          <td><%= ingredient.uom %></td>
        </tr>

      <% end %>

    </table>
  </div>
  <%= link_to '<button type="button">Edit</button>'.html_safe, edit_recipe_path %>
  <%= link_to '<button type="button">Back</button>'.html_safe, recipes_path %>
  <footer id = "footer">Team Eggplantbert: Alex Eby, Tristin Colenso, Ethan Large, Roman Formicola</footer>
</div>